### ISSUE TITLE
Can't inject with anything other than CreateThread

### ISSUE THREAD

**Issue by woah1337** [Akaion/Bleak#13] opened 2019-06-04 04:38 UTC
manualmap and hijackthread always close the process
get this while debugging (obviously couldn't call dllmain cause it closed the process lol)
https://i.imgur.com/7n9cJdJ.png

**Comment by woah1337** [comment] 2019-06-04 04:58
To replicate:
` byte[] dllByteArray = File.ReadAllBytes("qfqf.dll");
            using (Bleak.Injector injector = new Bleak.Injector(Bleak.InjectionMethod.CreateThread, "csgo", dllByteArray))
                injector.InjectDll();`
will not work at all if i specify dll path as a string instead of bytes ("qfqf" instead of dllByteArray), throws this exception 

> System.ComponentModel.Win32Exception: 'Failed to call LdrLoadDll in the remote process with error code 126'
and when i use bytes only createthread works.
compiling as debug x64

**Comment by Akaion** [comment] 2019-06-04 05:01
Gonna need to send me your DLL

**Comment by Colton1skees** [comment] 2019-06-05 20:22
I have the  exact same issue, which is fixed by passing the dll as a byte array instead of the dll name. However, I can't share my dll because its a P2C.

**Comment by Akaion** [comment] 2019-06-05 20:57
@Colton1skees It's impossible to know what the issue is without the DLL. Unless you wan't to step through the code yourself and figure out why its failing and let me know so I can fix it. Otherwise there is nothing I can do.

**Closed** 2019-06-10 12:11 UTC
